### ISSUE TITLE
Test failure on 0.1.0.5

### ISSUE THREAD

**Issue by mihaimaruseac** [aiya000/hs-throwable-exceptions#2]
Found on stackage nightly build. Full log:

```
  io exception prim
    can be shown in most cases:                                          OK
    can be thrown in all case:                                           OK
  index out of bounds exception
    finds the perpetrator with the clue:                                 ([10,11,12,13],4) looks like bad
OK
  general exception
    looks like other exception when GeneralException is executed `show`: FAIL
      expected: "MyTestException: nico-chan"
       but got: "MyTest: nico-chan"

1 out of 4 tests failed (0.00s)
```

**Comment by aiya000** [comment]
very thx ! :+1:

It is my temporary mistake :cry:

But, I already fixed in master's HEAD :smile:

I think it will be fixed in the next build of stackage :+1:

**Comment by mihaimaruseac** [comment]
Thanks

**Comment by mihaimaruseac** [comment]
You will actually have to upload the new version on Hackage. Stackage will pick it up and then I'll close this.

**Comment by aiya000** [comment]
I misunderstood x(

I uploaded to hackage !

**Comment by aiya000** [comment]
@mihaimaruseac Hi, thank you for helping so much !  
I could see hs-throwable-exceptions in [stackage](https://www.stackage.org/nightly-2017-07-21/package/throwable-exceptions-0.1.0.8).

Is this succeeding ? 🤔

**Comment by mihaimaruseac** [comment]
Yes, it succeeded. Thanks.

**Comment by aiya000** [comment]
Thanks !
